### PR TITLE
Fix two issues found by cppcheck/sonar

### PR DESCRIPTION
**Pull request by ralphlange**
This PR fixes two issues that keeps std from passing ITER's quality gates for non-essential software.

### CODE REVIEW

**Comment by ralphlange** [comment]
Ping!

**Comment by MarkRivers** [comment]
I have not forgotten about this.  It is complicated by the fact that @anjohnson  has created a new repository just for the scaler stuff.

https://github.com/epics-modules/scaler

So now the code in this PR is actually in 2 places, which is not a good thing. 

@timmmooney said he was OK with extracting the scaler code to a new module as Andrew has done.  So we should delete the scaler code from std and inform people that they need to use the new scaler module.

Should I delete the scaler code from std and @ralphlange make a new PR against that repository?

**Comment by ralphlange** [comment]
FWIW: The existing Pull Request in the scaler repository (codeathon work from February) has not been considered so far.

Despite that prognosis, I have created another Pull Request for the changes in question: epics-modules/scaler#2.
Please apply and/or reject as appropriate.

**Comment by MarkRivers** [comment]
I have merged both PRs in the scaler module.  I will merge this here, but I expect it will be obsolete because there is a pending PR to remove these scaler files from this repository.

**Pull request merged**
